components/timeline/post/components/user-comment/user-comment.jsx
components/timeline/post/components/user-comment/user-comment.module.scss
components/timeline/post/post.jsx
components/timeline/post/post.module.scss
package.json
pages/api/shopdatas.js
pages/api/shopdetail.js
pages/shopdetail/[id].js
pages/timeline.jsx
styles/timeline.module.scss
yarn.lock

/shopdetail/[id]でお店の詳細画面に必要なデータを渡すようにしました

shopdata動的ルーティング実装

---

components/timeline/post/components/user-comment/user-comment.jsx
components/timeline/post/post.jsx
pages/api/commentdatas.js
pages/timeline.jsx

ブランチ名を間違えていたので名前を変更して再pushしました
kanjiデータベース内に、利用者のコメントを保存するcommentdatasのコレクションを作成した。
commentdatasからコメントデータを取得して表示する機能を以下のファイルを作成/変更して実装した。
・pages/timeline.jsx
・components/timeline/post/post.jsx
・components/timeline/post/components/user-comment/user-comment.jsx
・pages/api/commentdatas.js

comment_disp(コメント表示機能の実装、再push)

---

components/timeline/post/components/user-comment/user-comment.jsx
components/timeline/post/post.jsx
pages/api/commentdatas.js
pages/timeline.jsx

kanjiデータベース内に、利用者のコメントを保存するcommentdatasのコレクションを作成した。
commentdatasからコメントデータを取得して表示する機能を以下のファイルを作成/変更して実装した。
・pages/timeline.jsx
・components/timeline/post/post.jsx
・components/timeline/post/components/user-comment/user-comment.jsx
・pages/api/commentdatas.js

comment_disp(コメント表示機能の実装)

---

components/timeline/post/components/plan/plan.jsx
components/timeline/post/components/plan/plan.module.scss
components/timeline/post/post.jsx
pages/api/plandatas.js
pages/timeline.jsx

kanjiデータベース内に、各店舗のプランを保存するplandatasのコレクションを作成した。
plandatasからプランデータを取得して表示する機能を以下のファイルを作成/変更して実装した。
・pages/timeline.jsx
・components/timeline/post/post.jsx
・components/timeline/post/components/plan/plan.jsx
・components/timeline/post/components/plan/plan.module.scss
・pages/api/plandatas.js

プラン表示機能の実装

---

components/timeline/post/components/menu/menu.jsx
components/timeline/post/components/menu/menu.module.scss
components/timeline/post/post.jsx
pages/timeline.jsx

以下のファイルを追加・変更を行いました。
・components/timeline/post/components/menu/menu.jsx
・components/timeline/post/components/menu/menu.module.scss
・components/timeline/post/post.jsx
・pages/timeline.jsx

メニューの表示機能の追加

---

components/timeline/post/components/plan/plan.jsx
pages/timeline.jsx

plan.jsxkeyエラー解消

---

components/shopplan/components/post.tsx
components/shopplan/components/tag.tsx
components/shopplan/shopplan.style.tsx
components/shopplan/shopplan.tsx
components/timeline/post/post.jsx
components/timeline/post/post.module.scss
components/userplan/components/post.tsx
components/userplan/components/up_post.style.ts
components/userplan/userplan.style.ts
components/userplan/userplan.tsx
pages/timeline.jsx
pages/userplan.tsx
styles/timeline.module.scss

プラン一覧・タイムライン画面のデザイン調整

---

components/shopplan/shopplan.style.tsx
components/shopplan/shopplan.tsx
components/timeline/post/post.module.scss
components/userplan/userplan.style.ts
components/userplan/userplan.tsx
pages/api/plansearch.js
pages/api/shopsearch.js
pages/timeline.jsx
styles/timeline.module.scss

プラン一覧・タイムラインの機能のみ実装

---

components/chat/components/plandetail/plandetail.style.tsx
components/chat/components/plandetail/plandetail.tsx
components/create_plan/create_plan.style.tsx
components/create_plan/create_plan.tsx

plandetailのデザインあて

---

components/shopplan/components/create-offer-modal/create-offer-modal.tsx
components/shopplan/components/sidebar_search.style.ts
components/shopplan/components/sidebar_search.tsx
components/shopplan/shopplan.style.tsx
components/shopplan/shopplan.tsx
components/timeline/post/components/picture/picture.style.ts
components/timeline/post/post.jsx
components/timeline/post/post.module.scss
components/timeline/tag.tsx
components/userplan/components/post.tsx
components/userplan/components/sidebar_search.style.ts
components/userplan/components/sidebar_search.tsx
components/userplan/components/tag.tsx
components/userplan/userplan.tsx
package.json
pages/api/plansearch.js
pages/timeline.jsx
styles/timeline.module.scss
yarn.lock

タイムライン画面のデザイン当て

---

components/chat/chat.style.ts
components/chat/chat.tsx
components/chat/components/offer-tab/offer-tab.style.ts
components/chat/components/offer-tab/offer-tab.tsx

plan_detailのデザインあてをしたので確認お願いします。

plan_detailのデザインあて

---

components/chat/components/plandetail/plandetail.style.tsx
components/header/header.style.ts
components/header/header.tsx

ヘッダーの調整とcssからstyle.tsへの完全移行したので確認お願いします。

ヘッダーの調整とcssからstyle.tsへの完全移行

---

components/create_plan/components/tag.tsx

プラン作成のタグ入力の修正

---

components/userplan/userplan.style.ts
components/userplan/userplan.tsx

幹事側プラン一覧の表示不具合修正

---

pages/timeline.jsx

timeline.jsx一部の記述修正

---

components/create_plan/components/tag.tsx
components/create_plan/create_plan.style.tsx

cleate_planのタグの調整

---

components/shopplan/components/sidebar_search.style.ts
components/shopplan/components/sidebar_search.tsx
components/shopplan/shopplan.tsx
components/timeline/post/post.jsx
components/userplan/components/post.tsx
components/userplan/components/sidebar_search.style.ts
components/userplan/components/sidebar_search.tsx
components/userplan/userplan.style.ts
styles/timeline.module.scss

タイムライン・プラン一覧のデザイン調整

---

components/shopplan/shopplan.style.tsx
components/shopplan/shopplan.tsx
components/timeline/post/post.jsx
pages/timeline.jsx

タイムラインにおける場所表示調整

---

components/shopplan/shopplan.tsx

店側プラン一覧の表示

---

components/shopplan/shopplan.tsx

店側プラン一覧表示調整

---

components/chat/components/plandetail/plandetail.style.tsx

オファー一覧のサイドバーにおけるタグ表示を複数行に対応

---

pages/api/shopsearch.js

タグ検索時のapiの参照コレクション名の修正

---

components/timeline/post/post.jsx
pages/api/shopsearch.js

新しいshopdatasの構造に合わせたタイムライン画面の検索機能

新しいshopdatasの構造に合わせたタイムライン画面の検索機能
